### PR TITLE
Update navigation with new branding

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

Update navigation with new branding

## QA

- Check out this feature branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8042/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/5634

### CODE REVIEW

**Comment by petesfrench** [comment]
Blocked by global-nav.

**Comment by minkyngkm** [comment]
@davegoddard42 The global nav has been updated. Could you take a look at the icon please?

**Comment by davegoddard42** [comment]
@minkyngkm there isn't a specific icon for Charmed OSM, so we should use the CoF, as you have done. I'm going to get that in writing though and update you here. Favicon needs doing also

**Comment by spencerbygraves** [comment]
@minkyngkm Looks good to me, thanks.

**Review by mtruj013 — APPROVED** [review]
LGTM!

**Pull request merged**
